services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    build: !reset null
    ports:
      - "0.0.0.0:8080:8080"
    restart: unless-stopped

  postgres:
    restart: unless-stopped

  rabbitmq:
    restart: unless-stopped
    ports: []
